Repository warnet-gi/WarnetBot, pull requests merged in 2023-10, with the labels that each got.

#87 Log admin message after being sent
  bot/cogs/admin.py
  bot/config/__init__.py
Labels: enhancement

#88 Prevent non booster to access the `/warnet-color` commands
  bot/cogs/color.py
  bot/cogs/ext/color/utils.py
Labels: bug

#90 Support custom delay on sticky command
  bot/cogs/sticky.py
  bot/data/db.sql
Labels: enhancement

#92 Fix bug on `/warnet-color` commands
  bot/cogs/color.py
  bot/cogs/ext/color/utils.py
Labels: bug

#95 Support sticky message on thread and handle new case
  bot/cogs/sticky.py
  bot/cogs/views/sticky.py
Labels: bug, enhancement

#97 Cache image generation
  bot/cogs/color.py
Labels: enhancement

#99 Fix bug on `/unix-timestamp` when `hour` or `minute` is set to 0
  bot/cogs/general.py
Labels: bug

#101 Implement TDD for General CMD
  .env.example
  .github/workflows/test.yml
  pyproject.toml
  requirements.txt
  tests/bot/cogs/test_general.py
Labels: enhancement, testing

#100 chore: initiate CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#105 Provide `id_only` option on `/rolemembers` command
  bot/cogs/general.py
  pyproject.toml
Labels: enhancement
