Repository warnet-gi/WarnetBot, pull requests merged in 2024-01, with the labels that each got.

#114 Feat/tatsu API integration
  .env.example
  bot/bot.py
  bot/cogs/booster.py
  bot/config/__init__.py
  bot/module/__init__.py
  bot/module/tatsu/README.md
  bot/module/tatsu/__init__.py
  bot/module/tatsu/data_structures.py
  bot/module/tatsu/error.py
  bot/module/tatsu/wrapper.py
  pyproject.toml
  requirements.txt
Labels: enhancement, priority

#116 Genshin RSS Feature
  bot/bot.py
  bot/cogs/genshin.py
  bot/config/genshin.py
  bot/data/genshin.json
  pyproject.toml
  requirements.txt
Labels: enhancement

#118 Make sure no articles are skipped for each task loop
  bot/cogs/genshin.py
Labels: bug
